
# 2021-10-22 issue with the pip utility (v3) getting overwritten by v2. had to
# purge python3-pip and reinstall to have both
- name: Install dnsgen
  pip:
    name: dnsgen
    state: latest
    executable: pip3

- name: Remove apt wfuzz
  apt:
      pkg: wfuzz
      state: absent

- name: Install wfuzz
  pip:
    name: wfuzz
    state: latest
    executable: pip3

- name: Remove apt impacket
  apt:
    pkg: impacket
    state: absent

- name: Install impacket
  pip:
    name: impacket
    state: latest
    executable: pip3

- name: Remove apt crackmapexec
  apt:
    pkg: crackmapexec
    state: absent
# hack: current cme doesn't work with greenlet v0.4.17
# see if we can ditch this
#- name: Install greenlet
#  pip:
#    name: greenlet
#    version: 0.4.16
#    executable: pip3
- name: Install crackmapexec
  pip:
    name: crackmapexec
    state: latest
    executable: pip3

- name: Install ldapdomaindump
  pip:
    name: ldapdomaindump
    state: latest
    executable: pip3

- name: Install bloodhound-python
  pip:
    name: bloodhound
    state: latest
    executable: pip3
