- name: install zsh
  apt:
      name: zsh
      state: present

- name: install tmux
  apt:
      name: tmux
      state: present

- name: install curl
  apt:
      name: curl
      state: present

- name: install vim
  apt:
      name: vim
      state: present

- name: install rsync
  apt:
      name: rsync
      state: present

- name: install git
  apt:
      name: git
      state: present

- name: install unattended-upgrades
  apt:
      name: unattended-upgrades
      state: present

- name: htop
  apt:
      name: htop
      state: present

- name: ufw
  apt:
      name: ufw
      state: present

