- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  become: yes
  register: upgrade_result

- name: Remove unused packages and their associated configurations
  ansible.builtin.apt:
    autoremove: yes
    purge: yes
  become: yes

- name: Clean the apt cache
  ansible.builtin.shell: apt-get clean -y
  become: yes

- name: Reboot the system if packages were upgraded
  ansible.builtin.reboot:
    reboot_timeout: 600  # Adjust the timeout as necessary
  become: yes
  when: upgrade_result.changed

- name: Wait for the system to become reachable again
  ansible.builtin.wait_for_connection:
    timeout: 300  # Adjust the timeout as necessary
  become: yes
  when: upgrade_result.changed
  