- name: attack setup
  hosts: all
  roles: 
   - network-scanner
#   - pkgs-cargo
   - pkgs-hack
   - go-get
   - msf-install

- import_playbook: playbook-pop-opt.yml
- import_playbook: playbook-pip-installs.yml
